import {StyleSheet, Dimensions} from 'react-native';
import {COLORS} from '../Constants';

const width = Dimensions.get('window').width;

const styles = StyleSheet.create({
  modalBodyStyle: {flex: 1, marginTop: 20, justifyContent: 'space-between'},
  modalHeaderTextStyle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.SECONDARY,
    alignSelf: 'center',
  },
  modalTextInputStyle: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: COLORS.LIGHT_GRAY,
    height: 50,
    padding: 10,
    marginTop: 20,
    width: '90%',
    alignSelf: 'center',
  },
  bottomViewStyle: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    height: 50,
  },
  customButtonStyle: {
    bottom: -25,
    borderColor: COLORS.PRIMARY,
    borderWidth: 0.2,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 25,
  },
  customButtonImageStyle: {height: 50, width: 50},
  mainContainer: {flex: 1, alignItems: 'center'},
  addButtonStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.SECONDARY,
    marginTop: 10,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 10,
    width: '90%',
  },
  addButtonTextStyle: {fontSize: 18, fontWeight: 'bold', color: COLORS.PRIMARY},
  modalComponentMainComponent: {
    backgroundColor: COLORS.PRIMARY,
    width: width - 60,
    borderRadius: 10,
  },
  cardComponentSubContainerStyle: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    flex: 1,
  },
  cardComponentSubContainerImageStyle: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 10,
  },
  imageBackgroundStyle: {flex: 1, width: '100%', height: 115, borderRadius: 10},
  cardCompontentStyle: {
    flex: 1,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: COLORS.PRIMARY_GRAY,
    shadowRadius: 12,
    shadowOpacity: 45,
    marginVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
    elevation: 2,
  },
  cardTextStyle: {
    fontSize: 14,
    lineHeight: 18,
  },
  cardTextStyle2: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 'bold',
    paddingBottom: 5,
  },
  cardTextStyle3: {fontSize: 25, lineHeight: 32, fontWeight: 'bold'},
  cardButtonStyle: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.SECONDARY_LIGHT,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardComponentButtonStyle: {
    display: 'flex',
    flexDirection: 'row',
    position: 'absolute',
    top: 10,
    right: 10,
    width: 60,
    justifyContent: 'space-between',
  },
  cardCompontentImageStyle: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 10,
  },
  cardComponentSubStyle: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '100%',
    flex: 1,
  },
  catListSubContainerStyle: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: 'lightgray',
    height: 40,
    padding: 10,
    marginTop: 20,
    marginBottom: 10,
    width: '90%',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  catListMainContainerStyle: {flex: 1, width: '100%', alignItems: 'center'},
  catListTextInputStyle: {
    paddingLeft: 5,
    width: '95%',
    height: 40,
    color: COLORS.SECONDARY,
  },
});

export default styles;
